// examples/vite-react/src/main.tsx
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';

import { IconProvider } from '@geniusaisolutions/icons/react';

import App from './App';
import { icons } from './ui.config';

const rootElement = document.getElementById('root');

if (!rootElement) {
  throw new Error('Missing #root element.');
}

createRoot(rootElement).render(
  <StrictMode>
    <IconProvider icons={icons}>
      <App />
    </IconProvider>
  </StrictMode>,
);

// examples/solid/src/index.jsx
import { render } from 'solid-js/web';

import { IconProvider } from '@geniusaisolutions/icons/solid';

import App from './App.jsx';
import { icons } from './ui.config.js';
import '../../shared/icon-example.css';

const root = document.getElementById('app');

if (!root) {
  throw new Error('Missing #app root.');
}

render(
  () => (
    <IconProvider icons={icons}>
      <App />
    </IconProvider>
  ),
  root,
);
