// src/solid/types.ts
import type { JSX, ParentProps, Component } from 'solid-js';

import type { BaseIconRenderProps, IconRegistry } from '../types';

export type SolidIconComponentProps = Omit<
  JSX.SvgSVGAttributes<SVGSVGElement>,
  'children' | 'ref'
> &
  BaseIconRenderProps;

export type SolidIconComponent = Component<SolidIconComponentProps>;

export type SolidIconRegistry = IconRegistry<SolidIconComponent>;

export interface IconProps extends SolidIconComponentProps {
  readonly name: string;
  readonly icons?: SolidIconRegistry | undefined;
}

export interface IconProviderProps extends ParentProps {
  readonly icons: SolidIconRegistry;
}

// src/react/types.ts
import type { ComponentType, ReactNode, SVGProps } from 'react';

import type { BaseIconRenderProps, IconRegistry } from '../types';

export type ReactIconComponentProps = Omit<
  SVGProps<SVGSVGElement>,
  'children' | 'ref'
> &
  BaseIconRenderProps;

export type ReactIconComponent = ComponentType<ReactIconComponentProps>;

export type ReactIconRegistry = IconRegistry<ReactIconComponent>;

export interface IconProps extends ReactIconComponentProps {
  readonly name: string;
  readonly icons?: ReactIconRegistry;
}

export interface IconProviderProps {
  readonly children: ReactNode;
  readonly icons: ReactIconRegistry;
}
