// examples/solid/src/App.jsx
import { createMemo, createSignal, For, Show } from 'solid-js';
import { Icon } from '@geniusaisolutions/icons/solid';

import { getVisibleIconNames, totalIcons } from './ui.config.js';

export default function App() {
  const [query, setQuery] = createSignal('');
  const visibleNames = createMemo(() => getVisibleIconNames(query()));

  return (
    <main class="page">
      <section class="hero">
        <h1>Solid example</h1>
        <p class="lede">
          This app registers <code>allIcons</code> once with the Solid adapter and
          renders the full built-in catalog with native <code>{'<Icon />'}</code>
          usage.
        </p>
      </section>

      <section class="controls">
        <label for="query">Search icon names</label>
        <input
          id="query"
          type="search"
          value={query()}
          onInput={(event) => setQuery(event.currentTarget.value)}
          placeholder="search, loader-2, book, alert, google..."
        />
      </section>

      <p class="stats">
        {visibleNames().length} of {totalIcons} icons visible
      </p>

      <Show
        when={visibleNames().length > 0}
        fallback={<p class="empty">{`No icons match "${query()}"`}</p>}
      >
        <section class="grid">
          <For each={visibleNames()}>
            {(name) => (
              <article class="card">
                <div class="stage">
                  <Icon name={name} aria-label={name} size={24} />
                </div>
                <div class="copy">
                  <p>{name}</p>
                  <code>{`<Icon name="${name}" />`}</code>
                </div>
              </article>
            )}
          </For>
        </section>
      </Show>
    </main>
  );
}

// examples/svelte/src/App.svelte
<script>
  import { Icon, IconProvider } from '@geniusaisolutions/icons/svelte';

  import { getVisibleIconNames, icons, totalIcons } from './ui.config.js';

  let query = '';

  $: visibleNames = getVisibleIconNames(query);
  $: emptyMessage = `No icons match "${query}"`;
</script>

<IconProvider {icons}>
  <main class="page">
    <section class="hero">
      <h1>Svelte example</h1>
      <p class="lede">
        This app registers <code>allIcons</code> once with the Svelte adapter and
        renders the full built-in catalog with native <code>&lt;Icon /&gt;</code>
        usage.
      </p>
    </section>

    <section class="controls">
      <label for="query">Search icon names</label>
      <input
        id="query"
        type="search"
        bind:value={query}
        placeholder="search, loader-2, book, alert, google..."
      />
    </section>

    <p class="stats">
      {visibleNames.length} of {totalIcons} icons visible
    </p>

    {#if visibleNames.length === 0}
      <p class="empty">{emptyMessage}</p>
    {:else}
      <section class="grid">
        {#each visibleNames as name}
          <article class="card">
            <div class="stage">
              <Icon name={name} size={24} aria-label={name} />
            </div>
            <div class="copy">
              <p>{name}</p>
              <code>{`<Icon name="${name}" />`}</code>
            </div>
          </article>
        {/each}
      </section>
    {/if}
  </main>
</IconProvider>
